
github: [KidiIT,KIDI-S-TECH]
patreon: KIDI'S-TECH
community_bridge:  GitHub Developer Program
custom: [https://github.com/enterprises/httpsgithubcomkidiit, https://github.com/KidiIT,https://github.com/KIDI-S-TECH]
